# ベースとなるPythonのイメージを指定
FROM python:3.11

# 作業ディレクトリを作成
WORKDIR /app

# 依存関係をインストールするためのファイルをコピー
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# プロジェクトの全ファイルをコピー
COPY . .

# FastAPIが使用するポートを開放
EXPOSE 8000

# uvicornサーバーを起動
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]